### ISSUE TITLE
Improve error message for missing handler

### ISSUE THREAD

**Issue by benjaminweb** [seanhess/hyperbole#30]
Take for example here is one handler missing:
```haskell
centralPage :: (Hyperbole :> es) => Maybe ResultVariant -> Page es '[Central, Presets, Results]
centralPage v = do
  -- message listens for any actions that the centralView triggers
  handle central $ handle presets $ load $ do
    pure $ do
      el bold "Message Page"
      hyper Central $ centralView A v
```

which raises this error:
```
    • Could not deduce ‘Handler Results :> es’
        arising from a use of ‘load’
      from the context: Hyperbole :> es
        bound by the type signature for:
                   centralPage :: forall (es :: [effectful-core-2.3.1.0:Effectful.Internal.Effect.Effect]).
                                  (Hyperbole :> es) =>
                                  Maybe ResultVariant -> Page es [Central, Presets, Results]
        at Table.hs:42:1-95
    • In the first argument of ‘($)’, namely ‘load’
      In the second argument of ‘($)’, namely
        ‘load
           $ do pure
                  $ do el bold "Message Page"
                       hyper Central $ centralView A v’
      In the second argument of ‘($)’, namely
        ‘handle presets
           $ load
               $ do pure
                      $ do el bold "Message Page"
                           hyper Central $ centralView A v’
   |
45 |   handle central $ handle presets $ load $ do
   |                                     ^^^^
```

The error message could be significantly more on-point to 

There might be [diagnose](https://hackage.haskell.org/package/diagnose) as option/inspiration.

(Also, don't knowing the implementation difficulty but listing all handlers as ordered list seems more intuitive for a user; I might see it too naive, but coming from a user's point of view here.)

**Comment by seanhess** [comment]
Also I hadn't thought of specifying handlers as a list, that's not a bad idea. Let me fool around with it. I'm not 100% happy with this compositional interface.

**Comment by benjaminweb** [comment]
"Type says X handlers but you defined Y handlers. Add missing handler Z."

**Comment by seanhess** [comment]
Oh, lists can't work, because the types are heterogenous.  `handle` adds an item to the page handlers: `Page (Handler id : es) total`. So we can't make a list of them, because those ids would all be different. We might be able to use a tuple though. Feel free to make a new issue for the `handle` / `load` interface design. Let's keep this one focused on the error message.

**Comment by benjaminweb** [comment]
Where can I catch this kind of error and define a more suitable one?
Could we take this as an example of how to write better errors for Hyperbole? Thinking of the developer's/contributor's section of the README.

**Comment by seanhess** [comment]
This would require some significant refactoring, because we're offloading to `Effectful` to make sure handlers are implemented as a custom effect: `Handler view`. 

We have lots of user-friendly custom type errors for views missing dependencies. See [HyperView.hs](https://github.com/seanhess/hyperbole/blob/main/src/Web/Hyperbole/HyperView.hs#L286). These are doable, because we use manual type families on the type-level list to make sure things are implemented correctly. 

I don't know an obvious way to create a custom type error for a constraint failing to solve. Do you? It might require refactoring to no longer use a single Effectful `Handler view` effect for each one. 

Have you run into the other custom type errors?

**Comment by benjaminweb** [comment]
> Have you run into the other custom type errors?
Not yet. But it sounds very much like it deserves its own label of issues here, doesn't it?

> I don't know an obvious way to create a custom type error for a constraint failing to solve. Do you? It might require refactoring to no longer use a single Effectful Handler view effect for each one.
I am afraid, not. Who most likely has it done and we could look into to see how they have done it?
I mean, _custom type error for a constraint failing to solve_ is pretty well worded requirement.

**Comment by seanhess** [comment]
I've googled it, and it doesn't seem possible without major refactoring. I'm going to close this for now as not worth the effort. Feel free to take a crack at a PR if you'd like. If we end up refactoring for #31 let's revisit
